---
extends: "eslint:recommended"

env:
  browser: true
  es6: true
  jasmine: true

parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    spread: true
    experimentalObjectRestSpread: true

plugins:
  - import
  - react
